
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Shreyansh Jain   ## put your name
title: 'Bachelor of Engineering'  ## your title
location: Bhilai (C.G.) , INDIA


## Social Profiles
facebook: http://www.facebook.com/bafna.shreyanshjain  ## your facebook account url
twitter: http://www.twitter.com/bafna_sb  ## your twitter account url
linkedin: http://www.linkedin.com/in/jshreyansh/  ## your linkedin account url
##dribbble: http://www.dribble.com  ## you dribbble account url
##foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
